<a href="https://colab.research.google.com/github/ArelliaAgustin/Desain-dan-Analisis-Algoritma/blob/main/Latihan_DAA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#slide6 latihan list
import datetime
x = datetime.datetime.now()

mahasiswa = ["Arellia Agustin",2022071060,"Informatika","Desain dan Analisis Algoritma",x,"UPJ"]
print(mahasiswa)

['Arellia Agustin', 2022071060, 'Informatika', 'Desain dan Analisis Algoritma', datetime.datetime(2023, 9, 11, 9, 2, 57, 281645), 'UPJ']


In [ ]:
#slide 8 cetak NIM masing-masing dengan memanggil urutan indeks dalam list mahasiswa
import datetime
x = datetime.datetime.now()

Mahasiswa = ["Arellia Agustin",2022071060,"Informatika","Desain dan Analisis Algoritma", x, "UPJ"]
Mahasiswa[1]

2022071060

In [ ]:
#slide 9 cetak nama universitas dengan memanggil urutan indeks dalam list mahasiswa
import datetime
x = datetime.datetime.now()

Mahasiswa = ["Arellia Agustin",2022071060,"Informatika","Desain dan Analisis Algoritma", x, "UPJ"]
Mahasiswa[5]

'UPJ'

In [ ]:
#slide 11 cetak NIM dan Prodi menggunakan slicing
#List Slicing
latihan=["Arellia Agustin",2022071060,"Informatika","Desain dan Analisis Algoritma", x, "UPJ"]
latihan[1:3]

[2022071060, 'Informatika']

In [ ]:
#slide 13 cetak isi list "mahasiswa", tambahkan kata "upj" didepan!
#latihan iterasi(pengulangan>for loop)
Mahasiswa = ["Arellia Agustin","Informatika","Desain dan Analisis Algoritma","UPJ"]
for aTambahan in Mahasiswa:
  print("UPJ "+aTambahan)

UPJ Arellia Agustin
UPJ Informatika
UPJ Desain dan Analisis Algoritma
UPJ UPJ


In [ ]:
#slide 15 susun tuple bernama "upj", isi dengan universitas, pembangunan, jaya
UPJ=('Universitas','Pembangunan','jaya')
UPJ[1:]

('Pembangunan', 'jaya')

In [ ]:
#slide 17
#buat tuple bersarang bernama "nested_tuple" dengan nilai:
#pertama=100, kedua=200,400,600, ketiga=300, keempat=400,800
pertama=("100")
kedua=("200","400","600")
ketiga=("300")
keempat=("400","800")

nested_tuple = (pertama,kedua,ketiga,keempat)
print(nested_tuple)

('100', ('200', '400', '600'), '300', ('400', '800'))


In [ ]:
#slide 21
#Latihan dictionary
mahasiswa={
    "Nama":"Arellia Agustin",
    "NIM":"2022071060",
    "Prodi":"Informatika",
    "Universitas":"UPJ"
}
print(mahasiswa)

{'Nama': 'Arellia Agustin', 'NIM': '2022071060', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [1]:
#slide 34 bagaimana menyusun ref sehingga mendapatkan hasil berikut
#>>>yellow|red {'dandelions','fire hydrant','blood','rose','leaves'}
#>>>yellow&red {'leaves','firehydrant'}
yellow = {'dandelions','fire hydrant','leaves'}
red = {'leaves', 'fire hydrant','rose','blood'}
print(yellow|red)
print(yellow&red)


{'leaves', 'fire hydrant', 'blood', 'dandelions', 'rose'}
{'leaves', 'fire hydrant'}


In [2]:
#slide 41 buat data frame bernama mahasiswa
import pandas as pd

data={
    "no":[1,2,3],
    "prodi": ["informatika","Sistem informasi","Teknik Sipil"],
    "Mahasiswa": [50 ,55 ,40],
    "lakilaki": [30,30,30],
    "Perembuan" : [20,25,10]
}
df = pd.DataFrame(data, index = ['-','-','-'])
print(df)


   no             prodi  Mahasiswa  lakilaki  Perembuan
-   1       informatika         50        30         20
-   2  Sistem informasi         55        30         25
-   3      Teknik Sipil         40        30         10


In [ ]:
#slide 44 Buatlah matrix & transpose matriks
import numpy as np
matriksA = np.array ([[100,200,300],
                      [700,600,500],
                      [900,1000,800]])

print("matriks A:")
print(matriksA)

transpose_matriks = np.transpose(matriksA)

print("Transpose Matriks A:")
print(transpose_matriks)

matriks A:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transpose Matriks A:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
